<?php
/**
 * Plugin Name: Make The Post Thumbnail Responsive
 * Plugin URI: https://1idweb.com/products/wordpress-plugin/wp1id-make-thepostthumbnail-responsive
 * Description: Eliminate `width` & `height` generated by `the_post_thumbnail()` on <img> tags
 * Version: 1.0
 * Author: Debjit Saha
 * Author URI: https://www.isitwp.com/remove-width-height-attributes-images-posts/
 * License: GPL2
 */

add_filter( 'post_thumbnail_html', 'remove_wps_width_attribute', 10 );
add_filter( 'image_send_to_editor', 'remove_wps_width_attribute', 10 );

function remove_wps_width_attribute( $html ) {
    $html = preg_replace( '/(width|height)=\"\d*\"\s/', "", $html );
    return $html;
}