<?php
/**
 * Plugin Name: 1id. Make The Post Thumbnail Responsive
 * Plugin URI:  https://1idweb.com/products/wordpress-plugin/wp1id-make-thepostthumbnail-responsive
 * Description: Eliminate &quot;width&quot; and &quot;height&quot; attributes generated by &quot;the_post_thumbnail()&quot; function on &lt;img&gt; tags. &#91;coded by 1idweb&#93;
 * Author:      Debjit Saha
 * Author URI:  https://www.isitwp.com/remove-width-height-attributes-images-posts/
 * License:     GPL2
 */

add_filter( 'post_thumbnail_html', 'remove_wps_width_attribute', 10 );
add_filter( 'image_send_to_editor', 'remove_wps_width_attribute', 10 );

function remove_wps_width_attribute( $html ) {
    $html = preg_replace( '/(width|height)=\"\d*\"\s/', "", $html );
    return $html;
}